---
server:
  port: 8080
  contextPath: /piccashop
  ssl:
    enabled: true
    key-store: demo_com_2018.jks
    key-alias: demo_com_2018
    key-store-password: 31067e22a7a8a6850be89d215fcdaab5
    ciphers: TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA
    enabled-protocols: TLSv1, TLSv1.1,TLSv1.2
    protocol: TLS
    client-auth: want
    tomcat:
      max-threads: 30
---
spring:
  profiles: local, default
---
datasource:
  url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
  username: SA
  password:
  driverClassName: org.h2.Driver
  defaultSchema:
  maxPoolSize: 10
#  hibernate:
#    hbm2ddl.method: create-drop
#    show_sql: true
#    format_sql: true
#    dialect: org.hibernate.dialect.H2Dialect

#for reports use this DB setup:
#jdbc:h2:tcp://localhost/mem:test
---
report: "/reports/ingredients.jasper"
